export namespace streams {
    export namespace files_folders_translations {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Locale = string;
export type Name = string;
export type Description = string;

export interface FilesFoldersTranslations {
  id: Id;
  entry_id: EntryId;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  locale: Locale;
  name?: Name;
  description?: Description;
  [k: string]: any;
}

    }
    export namespace applications {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type Name = string;
export type Reference = string;
export type Domain = string;
export type Enabled = number;

export interface Applications {
  id: Id;
  name: Name;
  reference: Reference;
  domain: Domain;
  enabled: Enabled;
  [k: string]: any;
}

    }
    export namespace activity_log_activity {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type LogName = string;
export type Description = string;
export type SubjectId = number;
export type SubjectType = string;
export type CauserId = number;
export type CauserType = string;
export type Properties = string;

export interface ActivityLogActivity {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  log_name: LogName;
  description: Description;
  subject_id?: SubjectId;
  subject_type?: SubjectType;
  causer_id?: CauserId;
  causer_type?: CauserType;
  properties?: Properties;
  [k: string]: any;
}

    }
    export namespace addons_extensions {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type Namespace = string;
export type Installed = number;
export type Enabled = number;

export interface AddonsExtensions {
  id: Id;
  namespace: Namespace;
  installed: Installed;
  enabled: Enabled;
  [k: string]: any;
}

    }
    export namespace addons_modules {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type Namespace = string;
export type Installed = number;
export type Enabled = number;

export interface AddonsModules {
  id: Id;
  namespace: Namespace;
  installed: Installed;
  enabled: Enabled;
  [k: string]: any;
}

    }
    export namespace cache {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Key = string;
export type Value = string;
export type Expiration = number;

export interface Cache {
  key: Key;
  value: Value;
  expiration: Expiration;
  [k: string]: any;
}

    }
    export namespace client_care_role_type_care {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Name = string;

export interface ClientCareRoleTypeCare {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  name?: Name;
  [k: string]: any;
}

    }
    export namespace client_courses_role_type_courses {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Name = string;

export interface ClientCoursesRoleTypeCourses {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  name?: Name;
  [k: string]: any;
}

    }
    export namespace client_requester_role_type_requester {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Name = string;

export interface ClientRequesterRoleTypeRequester {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  name?: Name;
  [k: string]: any;
}

    }
    export namespace client_volunteer_role_type_volunteer {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Name = string;

export interface ClientVolunteerRoleTypeVolunteer {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  name?: Name;
  [k: string]: any;
}

    }
    export namespace clients_advisors {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type UserId = number;
export type ClientId = number;
export type RoleId = number;
export type DepartmentId = number;

export interface ClientsAdvisors {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  user_id: UserId;
  client_id: ClientId;
  role_id: RoleId;
  department_id?: DepartmentId;
  [k: string]: any;
}

    }
    export namespace clients_clients {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type DeletedAt = string;
export type UserId = number;
export type Firstname = string;
export type Lastname = string;
export type Initials = string;
export type MaidenName = string;
export type Gender = string;
export type Birthdate = string;
export type Address = string;
export type Housenumber = string;
export type Postcode = string;
export type City = string;
export type Nationality = string;
export type MaritalStatus = string;
export type PhoneNumber = string;
export type MobileNumber = string;
export type Email = string;
export type BankAccountNumber = number;
export type ReceiveCorrespondence = number;
export type CorrespondenceAbout = string;
export type CorrespondenceVia = string;
export type Specials = string;
export type SignupDate = string;
export type Memo = string;

export interface ClientsClients {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  deleted_at?: DeletedAt;
  user_id?: UserId;
  firstname: Firstname;
  lastname: Lastname;
  initials?: Initials;
  maiden_name?: MaidenName;
  gender?: Gender;
  birthdate?: Birthdate;
  address?: Address;
  housenumber?: Housenumber;
  postcode?: Postcode;
  city?: City;
  nationality?: Nationality;
  marital_status?: MaritalStatus;
  phone_number?: PhoneNumber;
  mobile_number?: MobileNumber;
  email?: Email;
  bank_account_number?: BankAccountNumber;
  receive_correspondence?: ReceiveCorrespondence;
  correspondence_about?: CorrespondenceAbout;
  correspondence_via?: CorrespondenceVia;
  specials?: Specials;
  signup_date?: SignupDate;
  memo?: Memo;
  [k: string]: any;
}

    }
    export namespace clients_clients_advisors {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type RelatedId = number;
export type SortOrder = number;
export type DepartmentId = number;
export type RoleId = number;

export interface ClientsClientsAdvisors {
  id: Id;
  entry_id: EntryId;
  related_id: RelatedId;
  sort_order?: SortOrder;
  department_id: DepartmentId;
  role_id: RoleId;
  [k: string]: any;
}

    }
    export namespace clients_clients_departments {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type RelatedId = number;
export type SortOrder = number;

export interface ClientsClientsDepartments {
  id: Id;
  entry_id: EntryId;
  related_id: RelatedId;
  sort_order?: SortOrder;
  [k: string]: any;
}

    }
    export namespace clients_clients_roles {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type RelatedId = number;
export type DepartmentId = number;
export type SortOrder = number;

export interface ClientsClientsRoles {
  id: Id;
  entry_id: EntryId;
  related_id: RelatedId;
  department_id: DepartmentId;
  sort_order?: SortOrder;
  [k: string]: any;
}

    }
    export namespace clients_requester_role_type_requests {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Slug = string;

export interface ClientsRequesterRoleTypeRequests {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  slug: Slug;
  [k: string]: any;
}

    }
    export namespace clients_requester_role_type_requests_translations {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Locale = string;
export type Name = string;

export interface ClientsRequesterRoleTypeRequestsTranslations {
  id: Id;
  entry_id: EntryId;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  locale: Locale;
  name?: Name;
  [k: string]: any;
}

    }
    export namespace clients_roles {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Name = string;
export type Slug = string;
export type Type = string;
export type Color = string;
export type Description = string;

export interface ClientsRoles {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  name: Name;
  slug: Slug;
  type: Type;
  color?: Color;
  description?: Description;
  [k: string]: any;
}

    }
    export namespace configuration_configuration {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Scope = string;
export type Key = string;
export type Value = string;

export interface ConfigurationConfiguration {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  scope: Scope;
  key: Key;
  value?: Value;
  [k: string]: any;
}

    }
    export namespace cp_action_link_type_cp_action {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Key = string;

export interface CpActionLinkTypeCpAction {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  key: Key;
  [k: string]: any;
}

    }
    export namespace cp_action_link_type_cp_action_translations {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Locale = string;
export type Title = string;
export type Description = string;

export interface CpActionLinkTypeCpActionTranslations {
  id: Id;
  entry_id: EntryId;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  locale: Locale;
  title?: Title;
  description?: Description;
  [k: string]: any;
}

    }
    export namespace dashboard_dashboards {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type DeletedAt = string;
export type Slug = string;
export type Layout = string;

export interface DashboardDashboards {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  deleted_at?: DeletedAt;
  slug: Slug;
  layout: Layout;
  [k: string]: any;
}

    }
    export namespace dashboard_dashboards_allowed_roles {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type RelatedId = number;
export type SortOrder = number;

export interface DashboardDashboardsAllowedRoles {
  id: Id;
  entry_id: EntryId;
  related_id: RelatedId;
  sort_order?: SortOrder;
  [k: string]: any;
}

    }
    export namespace dashboard_dashboards_translations {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Locale = string;
export type Name = string;
export type Description = string;

export interface DashboardDashboardsTranslations {
  id: Id;
  entry_id: EntryId;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  locale: Locale;
  name?: Name;
  description?: Description;
  [k: string]: any;
}

    }
    export namespace dashboard_widgets {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type DeletedAt = string;
export type Extension = string;
export type Column = number;
export type DashboardId = number;
export type Pinned = number;

export interface DashboardWidgets {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  deleted_at?: DeletedAt;
  extension: Extension;
  column: Column;
  dashboard_id: DashboardId;
  pinned?: Pinned;
  [k: string]: any;
}

    }
    export namespace dashboard_widgets_allowed_roles {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type RelatedId = number;
export type SortOrder = number;

export interface DashboardWidgetsAllowedRoles {
  id: Id;
  entry_id: EntryId;
  related_id: RelatedId;
  sort_order?: SortOrder;
  [k: string]: any;
}

    }
    export namespace dashboard_widgets_translations {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Locale = string;
export type Title = string;
export type Description = string;

export interface DashboardWidgetsTranslations {
  id: Id;
  entry_id: EntryId;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  locale: Locale;
  title?: Title;
  description?: Description;
  [k: string]: any;
}

    }
    export namespace departments_associations {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type TargetId = number;
export type DepartmentId = number;
export type Mode = string;

export interface DepartmentsAssociations {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  target_id: TargetId;
  department_id: DepartmentId;
  mode: Mode;
  [k: string]: any;
}

    }
    export namespace departments_department {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type DeletedAt = string;
export type Name = string;
export type Slug = string;
export type Description = string;
export type Enabled = number;

export interface DepartmentsDepartment {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  deleted_at?: DeletedAt;
  name: Name;
  slug: Slug;
  description?: Description;
  enabled?: Enabled;
  [k: string]: any;
}

    }
    export namespace divider_link_type_dividers {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;

export interface DividerLinkTypeDividers {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  [k: string]: any;
}

    }
    export namespace failed_jobs {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type Connection = string;
export type Queue = string;
export type Payload = string;
export type Exception = string;
export type FailedAt = string;

export interface FailedJobs {
  id: Id;
  connection: Connection;
  queue: Queue;
  payload: Payload;
  exception: Exception;
  failed_at: FailedAt;
  [k: string]: any;
}

    }
    export namespace files_disks {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type DeletedAt = string;
export type Slug = string;
export type Adapter = string;

export interface FilesDisks {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  deleted_at?: DeletedAt;
  slug: Slug;
  adapter: Adapter;
  [k: string]: any;
}

    }
    export namespace files_disks_translations {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Locale = string;
export type Name = string;
export type Description = string;

export interface FilesDisksTranslations {
  id: Id;
  entry_id: EntryId;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  locale: Locale;
  name?: Name;
  description?: Description;
  [k: string]: any;
}

    }
    export namespace files_documents {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type DeletedAt = string;

export interface FilesDocuments {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  deleted_at?: DeletedAt;
  [k: string]: any;
}

    }
    export namespace files_documents_translations {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Locale = string;

export interface FilesDocumentsTranslations {
  id: Id;
  entry_id: EntryId;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  locale: Locale;
  [k: string]: any;
}

    }
    export namespace files_files {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type DeletedAt = string;
export type Name = string;
export type DiskId = number;
export type FolderId = number;
export type Extension = string;
export type Size = number;
export type MimeType = string;
export type EntryId = number;
export type EntryType = string;
export type Keywords = string;
export type Height = string;
export type Width = string;
export type AltText = string;
export type Title = string;
export type Caption = string;
export type Description = string;
export type StrId = string;

export interface FilesFiles {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  deleted_at?: DeletedAt;
  name: Name;
  disk_id: DiskId;
  folder_id: FolderId;
  extension: Extension;
  size: Size;
  mime_type: MimeType;
  entry_id?: EntryId;
  entry_type?: EntryType;
  keywords?: Keywords;
  height?: Height;
  width?: Width;
  alt_text?: AltText;
  title?: Title;
  caption?: Caption;
  description?: Description;
  str_id: StrId;
  [k: string]: any;
}

    }
    export namespace files_folders {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type DeletedAt = string;
export type DiskId = number;
export type Slug = string;
export type AllowedTypes = string;
export type StrId = string;

export interface FilesFolders {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  deleted_at?: DeletedAt;
  disk_id: DiskId;
  slug: Slug;
  allowed_types?: AllowedTypes;
  str_id: StrId;
  [k: string]: any;
}

    }
    export namespace applications_domains {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type ApplicationId = number;
export type Domain = string;
export type Locale = string;

export interface ApplicationsDomains {
  id: Id;
  application_id: ApplicationId;
  domain: Domain;
  locale: Locale;
  [k: string]: any;
}

    }
    export namespace files_images {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type DeletedAt = string;

export interface FilesImages {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  deleted_at?: DeletedAt;
  [k: string]: any;
}

    }
    export namespace files_images_translations {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Locale = string;

export interface FilesImagesTranslations {
  id: Id;
  entry_id: EntryId;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  locale: Locale;
  [k: string]: any;
}

    }
    export namespace header_link_type_headers {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;

export interface HeaderLinkTypeHeaders {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  [k: string]: any;
}

    }
    export namespace header_link_type_headers_translations {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Locale = string;
export type Title = string;

export interface HeaderLinkTypeHeadersTranslations {
  id: Id;
  entry_id: EntryId;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  locale: Locale;
  title?: Title;
  [k: string]: any;
}

    }
    export namespace jobs {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type Queue = string;
export type Payload = string;
export type Attempts = number;
export type ReservedAt = number;
export type AvailableAt = number;
export type CreatedAt = number;

export interface Jobs {
  id: Id;
  queue: Queue;
  payload: Payload;
  attempts: Attempts;
  reserved_at?: ReservedAt;
  available_at: AvailableAt;
  created_at: CreatedAt;
  [k: string]: any;
}

    }
    export namespace label_link_type_labels {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;

export interface LabelLinkTypeLabels {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  [k: string]: any;
}

    }
    export namespace label_link_type_labels_translations {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Locale = string;
export type Title = string;
export type Subtitle = string;
export type Description = string;

export interface LabelLinkTypeLabelsTranslations {
  id: Id;
  entry_id: EntryId;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  locale: Locale;
  title?: Title;
  subtitle?: Subtitle;
  description?: Description;
  [k: string]: any;
}

    }
    export namespace menus_links {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type DeletedAt = string;
export type MenuId = number;
export type Type = string;
export type EntryId = number;
export type EntryType = string;
export type Target = string;
export type Class = string;
export type ParentId = number;
export type Icon = string;

export interface MenusLinks {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  deleted_at?: DeletedAt;
  menu_id: MenuId;
  type: Type;
  entry_id: EntryId;
  entry_type: EntryType;
  target: Target;
  class?: Class;
  parent_id?: ParentId;
  icon?: Icon;
  [k: string]: any;
}

    }
    export namespace menus_links_allowed_roles {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type RelatedId = number;
export type SortOrder = number;

export interface MenusLinksAllowedRoles {
  id: Id;
  entry_id: EntryId;
  related_id: RelatedId;
  sort_order?: SortOrder;
  [k: string]: any;
}

    }
    export namespace menus_menus {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type DeletedAt = string;
export type Slug = string;

export interface MenusMenus {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  deleted_at?: DeletedAt;
  slug: Slug;
  [k: string]: any;
}

    }
    export namespace menus_menus_allowed_roles {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type RelatedId = number;
export type SortOrder = number;

export interface MenusMenusAllowedRoles {
  id: Id;
  entry_id: EntryId;
  related_id: RelatedId;
  sort_order?: SortOrder;
  [k: string]: any;
}

    }
    export namespace menus_menus_translations {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Locale = string;
export type Name = string;
export type Description = string;

export interface MenusMenusTranslations {
  id: Id;
  entry_id: EntryId;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  locale: Locale;
  name?: Name;
  description?: Description;
  [k: string]: any;
}

    }
    export namespace migrations {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type Migration = string;
export type Batch = number;

export interface Migrations {
  id: Id;
  migration: Migration;
  batch: Batch;
  [k: string]: any;
}

    }
    export namespace module_link_type_modules {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Key = string;

export interface ModuleLinkTypeModules {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  key: Key;
  [k: string]: any;
}

    }
    export namespace module_link_type_modules_translations {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Locale = string;
export type Title = string;
export type Description = string;

export interface ModuleLinkTypeModulesTranslations {
  id: Id;
  entry_id: EntryId;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  locale: Locale;
  title?: Title;
  description?: Description;
  [k: string]: any;
}

    }
    export namespace notifications {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = string;
export type Type = string;
export type NotifiableType = string;
export type NotifiableId = number;
export type Data = string;
export type ReadAt = string;
export type CreatedAt = string;
export type UpdatedAt = string;

export interface Notifications {
  id: Id;
  type: Type;
  notifiable_type: NotifiableType;
  notifiable_id: NotifiableId;
  data: Data;
  read_at?: ReadAt;
  created_at?: CreatedAt;
  updated_at?: UpdatedAt;
  [k: string]: any;
}

    }
    export namespace preferences_preferences {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type UserId = number;
export type Key = string;
export type Value = string;

export interface PreferencesPreferences {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  user_id: UserId;
  key: Key;
  value?: Value;
  [k: string]: any;
}

    }
    export namespace search_items {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Title = string;
export type Description = string;
export type Keywords = string;
export type EntryId = number;
export type EntryType = string;
export type StreamId = number;
export type Locale = string;
export type Searchable = string;

export interface SearchItems {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  title?: Title;
  description?: Description;
  keywords?: Keywords;
  entry_id: EntryId;
  entry_type: EntryType;
  stream_id: StreamId;
  locale: Locale;
  searchable?: Searchable;
  [k: string]: any;
}

    }
    export namespace sessions {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = string;
export type UserId = number;
export type IpAddress = string;
export type UserAgent = string;
export type Payload = string;
export type LastActivity = number;

export interface Sessions {
  id: Id;
  user_id?: UserId;
  ip_address?: IpAddress;
  user_agent?: UserAgent;
  payload: Payload;
  last_activity: LastActivity;
  [k: string]: any;
}

    }
    export namespace settings_settings {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Key = string;
export type Value = string;

export interface SettingsSettings {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  key: Key;
  value?: Value;
  [k: string]: any;
}

    }
    export namespace streams_assignments {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type StreamId = number;
export type FieldId = number;
export type Config = string;
export type Unique = number;
export type Required = number;
export type Searchable = number;
export type Translatable = number;
export type Versionable = number;

export interface StreamsAssignments {
  id: Id;
  sort_order: SortOrder;
  stream_id: StreamId;
  field_id: FieldId;
  config: Config;
  unique: Unique;
  required: Required;
  searchable: Searchable;
  translatable: Translatable;
  versionable: Versionable;
  [k: string]: any;
}

    }
    export namespace streams_assignments_translations {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type AssignmentId = number;
export type Locale = string;
export type Label = string;
export type Warning = string;
export type Placeholder = string;
export type Instructions = string;

export interface StreamsAssignmentsTranslations {
  id: Id;
  assignment_id: AssignmentId;
  locale: Locale;
  label?: Label;
  warning?: Warning;
  placeholder?: Placeholder;
  instructions?: Instructions;
  [k: string]: any;
}

    }
    export namespace streams_fields {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type Namespace = string;
export type Slug = string;
export type Type = string;
export type Config = string;
export type Locked = number;

export interface StreamsFields {
  id: Id;
  namespace: Namespace;
  slug: Slug;
  type: Type;
  config: Config;
  locked: Locked;
  [k: string]: any;
}

    }
    export namespace streams_fields_translations {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type FieldId = number;
export type Locale = string;
export type Name = string;
export type Placeholder = string;
export type Warning = string;
export type Instructions = string;

export interface StreamsFieldsTranslations {
  id: Id;
  field_id: FieldId;
  locale: Locale;
  name?: Name;
  placeholder?: Placeholder;
  warning?: Warning;
  instructions?: Instructions;
  [k: string]: any;
}

    }
    export namespace streams_locks {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type LockedAt = string;
export type LockedById = number;
export type LockableId = number;
export type LockableType = string;
export type Url = string;

export interface StreamsLocks {
  id: Id;
  locked_at: LockedAt;
  locked_by_id: LockedById;
  lockable_id: LockableId;
  lockable_type: LockableType;
  url: Url;
  [k: string]: any;
}

    }
    export namespace streams_streams {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type Namespace = string;
export type Slug = string;
export type Prefix = string;
export type TitleColumn = string;
export type OrderBy = string;
export type Locked = number;
export type Hidden = number;
export type Sortable = number;
export type Searchable = number;
export type Trashable = number;
export type Translatable = number;
export type Versionable = number;
export type Config = string;

export interface StreamsStreams {
  id: Id;
  sort_order?: SortOrder;
  namespace: Namespace;
  slug: Slug;
  prefix?: Prefix;
  title_column: TitleColumn;
  order_by: OrderBy;
  locked: Locked;
  hidden: Hidden;
  sortable: Sortable;
  searchable: Searchable;
  trashable: Trashable;
  translatable: Translatable;
  versionable: Versionable;
  config: Config;
  [k: string]: any;
}

    }
    export namespace streams_streams_translations {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type StreamId = number;
export type Locale = string;
export type Name = string;
export type Description = string;

export interface StreamsStreamsTranslations {
  id: Id;
  stream_id: StreamId;
  locale: Locale;
  name?: Name;
  description?: Description;
  [k: string]: any;
}

    }
    export namespace streams_versions {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Version = number;
export type CreatedAt = string;
export type CreatedById = number;
export type VersionableId = number;
export type VersionableType = string;
export type IpAddress = string;
export type Model = string;
export type Data = string;

export interface StreamsVersions {
  version: Version;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  versionable_id: VersionableId;
  versionable_type: VersionableType;
  ip_address: IpAddress;
  model: Model;
  data: Data;
  [k: string]: any;
}

    }
    export namespace test {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type UserId = number;
export type ClientId = number;
export type DepartmentId = number;
export type RoleId = number;

export interface Test {
  id: Id;
  user_id: UserId;
  client_id: ClientId;
  department_id: DepartmentId;
  role_id: RoleId;
  [k: string]: any;
}

    }
    export namespace url_link_type_urls {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Url = string;

export interface UrlLinkTypeUrls {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  url: Url;
  [k: string]: any;
}

    }
    export namespace url_link_type_urls_translations {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Locale = string;
export type Title = string;
export type Description = string;

export interface UrlLinkTypeUrlsTranslations {
  id: Id;
  entry_id: EntryId;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  locale: Locale;
  title?: Title;
  description?: Description;
  [k: string]: any;
}

    }
    export namespace users_roles {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type DeletedAt = string;
export type Slug = string;
export type Permissions = string;

export interface UsersRoles {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  deleted_at?: DeletedAt;
  slug: Slug;
  permissions?: Permissions;
  [k: string]: any;
}

    }
    export namespace users_roles_translations {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Locale = string;
export type Name = string;
export type Description = string;

export interface UsersRolesTranslations {
  id: Id;
  entry_id: EntryId;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  locale: Locale;
  name?: Name;
  description?: Description;
  [k: string]: any;
}

    }
    export namespace users_users {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type DeletedAt = string;
export type DepartmentId = number;
export type Email = string;
export type Username = string;
export type Password = string;
export type DisplayName = string;
export type FirstName = string;
export type LastName = string;
export type Activated = number;
export type Enabled = number;
export type Permissions = string;
export type LastLoginAt = string;
export type RememberToken = string;
export type ActivationCode = string;
export type ResetCode = string;
export type LastActivityAt = string;
export type IpAddress = string;
export type StrId = string;

export interface UsersUsers {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  deleted_at?: DeletedAt;
  department_id?: DepartmentId;
  email: Email;
  username: Username;
  password: Password;
  display_name: DisplayName;
  first_name?: FirstName;
  last_name?: LastName;
  activated?: Activated;
  enabled?: Enabled;
  permissions?: Permissions;
  last_login_at?: LastLoginAt;
  remember_token?: RememberToken;
  activation_code?: ActivationCode;
  reset_code?: ResetCode;
  last_activity_at?: LastActivityAt;
  ip_address?: IpAddress;
  str_id: StrId;
  [k: string]: any;
}

    }
    export namespace users_users_departments {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type RelatedId = number;
export type SortOrder = number;

export interface UsersUsersDepartments {
  id: Id;
  entry_id: EntryId;
  related_id: RelatedId;
  sort_order?: SortOrder;
  [k: string]: any;
}

    }
    export namespace users_users_roles {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type RelatedId = number;
export type SortOrder = number;

export interface UsersUsersRoles {
  id: Id;
  entry_id: EntryId;
  related_id: RelatedId;
  sort_order?: SortOrder;
  [k: string]: any;
}

    }
}