export namespace streams {
    export namespace applications {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type Name = string;
export type Reference = string;
export type Domain = string;
export type Enabled = number;

export interface Applications {
  id: Id;
  name: Name;
  reference: Reference;
  domain: Domain;
  enabled: Enabled;
  [k: string]: any;
}

    }
    export namespace applications_domains {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type ApplicationId = number;
export type Domain = string;
export type Locale = string;

export interface ApplicationsDomains {
  id: Id;
  application_id: ApplicationId;
  domain: Domain;
  locale: Locale;
  [k: string]: any;
}

    }
    export namespace activities_activity {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Name = string;
export type AvailableForReuse = number;
export type Description = string;
export type Organiser = string;
export type Location = string;
export type StartsAt = string;
export type EndsAt = string;
export type MinParticipants = number;
export type MaxParticipants = number;
export type PaymentPrice = number;
export type PaymentPeriod = string;
export type PaymentInvoiceType = string;
export type PaymentMethod = string;
export type LogTotalContacts = number;
export type LogNewContacts = number;
export type LogTotalVrijwilligers = number;
export type LogTotalInterventions = number;
export type LogDescription = string;
export type LogCalamities = string;

export interface ActivitiesActivity {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  name: Name;
  available_for_reuse?: AvailableForReuse;
  description?: Description;
  organiser?: Organiser;
  location?: Location;
  starts_at?: StartsAt;
  ends_at?: EndsAt;
  min_participants?: MinParticipants;
  max_participants?: MaxParticipants;
  payment_price?: PaymentPrice;
  payment_period?: PaymentPeriod;
  payment_invoice_type?: PaymentInvoiceType;
  payment_method?: PaymentMethod;
  log_total_contacts?: LogTotalContacts;
  log_new_contacts?: LogNewContacts;
  log_total_vrijwilligers?: LogTotalVrijwilligers;
  log_total_interventions?: LogTotalInterventions;
  log_description?: LogDescription;
  log_calamities?: LogCalamities;
  [k: string]: any;
}

    }
    export namespace activity_log_activity {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type LogName = string;
export type Description = string;
export type SubjectId = number;
export type SubjectType = string;
export type CauserId = number;
export type CauserType = string;
export type Properties = string;

export interface ActivityLogActivity {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  log_name: LogName;
  description: Description;
  subject_id?: SubjectId;
  subject_type?: SubjectType;
  causer_id?: CauserId;
  causer_type?: CauserType;
  properties?: Properties;
  [k: string]: any;
}

    }
    export namespace addons_extensions {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type Namespace = string;
export type Installed = number;
export type Enabled = number;

export interface AddonsExtensions {
  id: Id;
  namespace: Namespace;
  installed: Installed;
  enabled: Enabled;
  [k: string]: any;
}

    }
    export namespace addons_modules {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type Namespace = string;
export type Installed = number;
export type Enabled = number;

export interface AddonsModules {
  id: Id;
  namespace: Namespace;
  installed: Installed;
  enabled: Enabled;
  [k: string]: any;
}

    }
    export namespace cache {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Key = string;
export type Value = string;
export type Expiration = number;

export interface Cache {
  key: Key;
  value: Value;
  expiration: Expiration;
  [k: string]: any;
}

    }
    export namespace caretaker_role_type_intake {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type ClientId = number;
export type IntakeDate = string;
export type RedirectingInstanceId = number;
export type CustomRedirectingInstance = string;
export type Contact = string;
export type Phone = string;
export type Email = string;
export type CustomInvolvedInstances = string;
export type Situation = string;
export type HoursPerWeekId = number;
export type CustomCaregivers = string;
export type CustomRestrictions = string;
export type CustomProvidedCare = string;
export type OverpressureStart = string;
export type OverpressureWish = string;
export type OverpressureActual = string;
export type CustomOverpressure = string;
export type OverpressureNotes = string;

export interface CaretakerRoleTypeIntake {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  client_id?: ClientId;
  intake_date?: IntakeDate;
  redirecting_instance_id?: RedirectingInstanceId;
  custom_redirecting_instance?: CustomRedirectingInstance;
  contact?: Contact;
  phone?: Phone;
  email?: Email;
  custom_involved_instances?: CustomInvolvedInstances;
  situation?: Situation;
  hours_per_week_id?: HoursPerWeekId;
  custom_caregivers?: CustomCaregivers;
  custom_restrictions?: CustomRestrictions;
  custom_provided_care?: CustomProvidedCare;
  overpressure_start?: OverpressureStart;
  overpressure_wish?: OverpressureWish;
  overpressure_actual?: OverpressureActual;
  custom_overpressure?: CustomOverpressure;
  overpressure_notes?: OverpressureNotes;
  [k: string]: any;
}

    }
    export namespace caretaker_role_type_intake_caregivers {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Name = string;
export type Slug = string;
export type Enabled = number;

export interface CaretakerRoleTypeIntakeCaregivers {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  name: Name;
  slug: Slug;
  enabled?: Enabled;
  [k: string]: any;
}

    }
    export namespace caretaker_role_type_intake_hours {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Name = string;
export type Slug = string;
export type Enabled = number;

export interface CaretakerRoleTypeIntakeHours {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  name: Name;
  slug: Slug;
  enabled?: Enabled;
  [k: string]: any;
}

    }
    export namespace caretaker_role_type_intake_intake_caregivers {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type RelatedId = number;
export type SortOrder = number;

export interface CaretakerRoleTypeIntakeIntakeCaregivers {
  id: Id;
  entry_id: EntryId;
  related_id: RelatedId;
  sort_order?: SortOrder;
  [k: string]: any;
}

    }
    export namespace caretaker_role_type_intake_intake_overpressure {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type RelatedId = number;
export type SortOrder = number;

export interface CaretakerRoleTypeIntakeIntakeOverpressure {
  id: Id;
  entry_id: EntryId;
  related_id: RelatedId;
  sort_order?: SortOrder;
  [k: string]: any;
}

    }
    export namespace caretaker_role_type_intake_intake_provided_care {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type RelatedId = number;
export type SortOrder = number;

export interface CaretakerRoleTypeIntakeIntakeProvidedCare {
  id: Id;
  entry_id: EntryId;
  related_id: RelatedId;
  sort_order?: SortOrder;
  [k: string]: any;
}

    }
    export namespace caretaker_role_type_intake_intake_restrictions {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type RelatedId = number;
export type SortOrder = number;

export interface CaretakerRoleTypeIntakeIntakeRestrictions {
  id: Id;
  entry_id: EntryId;
  related_id: RelatedId;
  sort_order?: SortOrder;
  [k: string]: any;
}

    }
    export namespace caretaker_role_type_intake_involved_instances {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type RelatedId = number;
export type SortOrder = number;

export interface CaretakerRoleTypeIntakeInvolvedInstances {
  id: Id;
  entry_id: EntryId;
  related_id: RelatedId;
  sort_order?: SortOrder;
  [k: string]: any;
}

    }
    export namespace caretaker_role_type_intake_overpressure {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type RelatedId = number;
export type SortOrder = number;

export interface CaretakerRoleTypeIntakeOverpressure {
  id: Id;
  entry_id: EntryId;
  related_id: RelatedId;
  sort_order?: SortOrder;
  [k: string]: any;
}

    }
    export namespace caretaker_role_type_intake_overpressures {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Name = string;
export type Slug = string;
export type Enabled = number;

export interface CaretakerRoleTypeIntakeOverpressures {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  name: Name;
  slug: Slug;
  enabled?: Enabled;
  [k: string]: any;
}

    }
    export namespace caretaker_role_type_intake_provided_care {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Name = string;
export type Slug = string;
export type Enabled = number;

export interface CaretakerRoleTypeIntakeProvidedCare {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  name: Name;
  slug: Slug;
  enabled?: Enabled;
  [k: string]: any;
}

    }
    export namespace caretaker_role_type_intake_restrictions {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Name = string;
export type Slug = string;
export type Enabled = number;

export interface CaretakerRoleTypeIntakeRestrictions {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  name: Name;
  slug: Slug;
  enabled?: Enabled;
  [k: string]: any;
}

    }
    export namespace client_registrations_actions {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Name = string;
export type Slug = string;
export type Enabled = number;

export interface ClientRegistrationsActions {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  name: Name;
  slug: Slug;
  enabled?: Enabled;
  [k: string]: any;
}

    }
    export namespace client_registrations_categories {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Name = string;
export type RoleId = number;

export interface ClientRegistrationsCategories {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  name: Name;
  role_id: RoleId;
  [k: string]: any;
}

    }
    export namespace client_registrations_registrations {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type ClientId = number;
export type RoleId = number;
export type SubjectId = number;
export type ContactMethod = string;
export type ContactThrough = string;
export type RegistrationDate = string;
export type Body = string;
export type Confidential = string;
export type Duration = string;
export type Follow = number;
export type FollowDate = string;
export type FollowInformation = string;
export type FollowUserId = number;
export type DepartmentId = number;

export interface ClientRegistrationsRegistrations {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  client_id: ClientId;
  role_id: RoleId;
  subject_id: SubjectId;
  contact_method?: ContactMethod;
  contact_through?: ContactThrough;
  registration_date?: RegistrationDate;
  body?: Body;
  confidential?: Confidential;
  duration?: Duration;
  follow?: Follow;
  follow_date?: FollowDate;
  follow_information?: FollowInformation;
  follow_user_id?: FollowUserId;
  department_id?: DepartmentId;
  [k: string]: any;
}

    }
    export namespace client_registrations_reports {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type ReportDate = string;
export type RegistrationId = number;
export type AdvisorId = number;
export type ContactMethod = string;
export type ContactThrough = string;
export type ActionId = number;
export type Body = string;
export type Confidential = string;
export type Duration = string;
export type Follow = number;
export type FollowDate = string;
export type FollowInformation = string;
export type FollowUserId = number;

export interface ClientRegistrationsReports {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  report_date?: ReportDate;
  registration_id: RegistrationId;
  advisor_id: AdvisorId;
  contact_method?: ContactMethod;
  contact_through?: ContactThrough;
  action_id?: ActionId;
  body?: Body;
  confidential?: Confidential;
  duration?: Duration;
  follow?: Follow;
  follow_date?: FollowDate;
  follow_information?: FollowInformation;
  follow_user_id?: FollowUserId;
  [k: string]: any;
}

    }
    export namespace client_registrations_subjects {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Name = string;
export type CategoryId = number;

export interface ClientRegistrationsSubjects {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  name: Name;
  category_id: CategoryId;
  [k: string]: any;
}

    }
    export namespace clients_clients {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type DeletedAt = string;
export type UserId = number;
export type Firstname = string;
export type Lastname = string;
export type Initials = string;
export type MaidenName = string;
export type Gender = string;
export type BirthDate = string;
export type Address = string;
export type Housenumber = string;
export type Postcode = string;
export type City = string;
export type Nationality = string;
export type MaritalStatus = string;
export type PhoneNumber = string;
export type MobileNumber = string;
export type Email = string;
export type BankAccountNumber = number;
export type ReceiveCorrespondence = number;
export type CorrespondenceAbout = string;
export type CorrespondenceVia = string;
export type Specials = string;
export type SignupDate = string;
export type Memo = string;
export type DocumentFolderId = number;

export interface ClientsClients {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  deleted_at?: DeletedAt;
  user_id?: UserId;
  firstname: Firstname;
  lastname: Lastname;
  initials?: Initials;
  maiden_name?: MaidenName;
  gender?: Gender;
  birth_date?: BirthDate;
  address?: Address;
  housenumber?: Housenumber;
  postcode?: Postcode;
  city?: City;
  nationality?: Nationality;
  marital_status?: MaritalStatus;
  phone_number?: PhoneNumber;
  mobile_number?: MobileNumber;
  email?: Email;
  bank_account_number?: BankAccountNumber;
  receive_correspondence?: ReceiveCorrespondence;
  correspondence_about?: CorrespondenceAbout;
  correspondence_via?: CorrespondenceVia;
  specials?: Specials;
  signup_date?: SignupDate;
  memo?: Memo;
  document_folder_id?: DocumentFolderId;
  [k: string]: any;
}

    }
    export namespace clients_clients_activities {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type RelatedId = number;
export type SortOrder = number;

export interface ClientsClientsActivities {
  id: Id;
  entry_id: EntryId;
  related_id: RelatedId;
  sort_order?: SortOrder;
  [k: string]: any;
}

    }
    export namespace clients_clients_advisors {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type RelatedId = number;
export type SortOrder = number;
export type DepartmentId = number;
export type RoleId = number;

export interface ClientsClientsAdvisors {
  id: Id;
  entry_id: EntryId;
  related_id: RelatedId;
  sort_order?: SortOrder;
  department_id: DepartmentId;
  role_id: RoleId;
  [k: string]: any;
}

    }
    export namespace clients_clients_departments {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type RelatedId = number;
export type SortOrder = number;

export interface ClientsClientsDepartments {
  id: Id;
  entry_id: EntryId;
  related_id: RelatedId;
  sort_order?: SortOrder;
  [k: string]: any;
}

    }
    export namespace clients_clients_documents {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type FileId = number;
export type SortOrder = number;

export interface ClientsClientsDocuments {
  id: Id;
  entry_id: EntryId;
  file_id: FileId;
  sort_order?: SortOrder;
  [k: string]: any;
}

    }
    export namespace clients_clients_groups {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type RelatedId = number;
export type SortOrder = number;

export interface ClientsClientsGroups {
  id: Id;
  entry_id: EntryId;
  related_id: RelatedId;
  sort_order?: SortOrder;
  [k: string]: any;
}

    }
    export namespace clients_clients_roles {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type RelatedId = number;
export type DepartmentId = number;
export type SortOrder = number;

export interface ClientsClientsRoles {
  id: Id;
  entry_id: EntryId;
  related_id: RelatedId;
  department_id: DepartmentId;
  sort_order?: SortOrder;
  [k: string]: any;
}

    }
    export namespace clients_groups {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Name = string;
export type UserId = number;
export type DepartmentId = number;
export type Description = string;
export type GroupTarget = string;
export type InvolvedParticipants = number;
export type GroupField_1 = string;
export type GroupField_2 = string;
export type GroupField_3 = string;

export interface ClientsGroups {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  name: Name;
  user_id?: UserId;
  department_id?: DepartmentId;
  description?: Description;
  group_target?: GroupTarget;
  involved_participants?: InvolvedParticipants;
  group_field_1?: GroupField_1;
  group_field_2?: GroupField_2;
  group_field_3?: GroupField_3;
  [k: string]: any;
}

    }
    export namespace clients_instances {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Name = string;
export type Slug = string;

export interface ClientsInstances {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  name: Name;
  slug: Slug;
  [k: string]: any;
}

    }
    export namespace clients_roles {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Name = string;
export type Slug = string;
export type Type = string;
export type Color = string;
export type Description = string;

export interface ClientsRoles {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  name: Name;
  slug: Slug;
  type: Type;
  color?: Color;
  description?: Description;
  [k: string]: any;
}

    }
    export namespace configuration_configuration {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Scope = string;
export type Key = string;
export type Value = string;

export interface ConfigurationConfiguration {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  scope: Scope;
  key: Key;
  value?: Value;
  [k: string]: any;
}

    }
    export namespace contacts_contacts {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Type = string;
export type ClientId = number;
export type Firstname = string;
export type Insertion = string;
export type Lastname = string;
export type Gender = string;
export type Address = string;
export type Housenumber = string;
export type HousenumberSuffix = string;
export type Postcode = string;
export type City = string;
export type PhoneNumber = string;
export type MobileNumber = string;
export type Email = string;
export type Extra = string;
export type SignupDate = string;

export interface ContactsContacts {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  type: Type;
  client_id?: ClientId;
  firstname?: Firstname;
  insertion?: Insertion;
  lastname?: Lastname;
  gender?: Gender;
  address?: Address;
  housenumber?: Housenumber;
  housenumber_suffix?: HousenumberSuffix;
  postcode?: Postcode;
  city?: City;
  phone_number?: PhoneNumber;
  mobile_number?: MobileNumber;
  email?: Email;
  extra?: Extra;
  signup_date?: SignupDate;
  [k: string]: any;
}

    }
    export namespace core_education_levels {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Name = string;
export type Slug = string;

export interface CoreEducationLevels {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  name: Name;
  slug: Slug;
  [k: string]: any;
}

    }
    export namespace core_instances {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Name = string;
export type Slug = string;

export interface CoreInstances {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  name: Name;
  slug: Slug;
  [k: string]: any;
}

    }
    export namespace courses_role_type_intake {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;

export interface CoursesRoleTypeIntake {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  [k: string]: any;
}

    }
    export namespace courses_role_type_intake_translations {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Locale = string;

export interface CoursesRoleTypeIntakeTranslations {
  id: Id;
  entry_id: EntryId;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  locale: Locale;
  [k: string]: any;
}

    }
    export namespace cp_action_link_type_cp_action {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Key = string;

export interface CpActionLinkTypeCpAction {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  key: Key;
  [k: string]: any;
}

    }
    export namespace cp_action_link_type_cp_action_translations {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Locale = string;
export type Title = string;
export type Description = string;

export interface CpActionLinkTypeCpActionTranslations {
  id: Id;
  entry_id: EntryId;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  locale: Locale;
  title?: Title;
  description?: Description;
  [k: string]: any;
}

    }
    export namespace dashboard_dashboards {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type DeletedAt = string;
export type Slug = string;
export type Layout = string;

export interface DashboardDashboards {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  deleted_at?: DeletedAt;
  slug: Slug;
  layout: Layout;
  [k: string]: any;
}

    }
    export namespace dashboard_dashboards_allowed_roles {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type RelatedId = number;
export type SortOrder = number;

export interface DashboardDashboardsAllowedRoles {
  id: Id;
  entry_id: EntryId;
  related_id: RelatedId;
  sort_order?: SortOrder;
  [k: string]: any;
}

    }
    export namespace dashboard_dashboards_translations {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Locale = string;
export type Name = string;
export type Description = string;

export interface DashboardDashboardsTranslations {
  id: Id;
  entry_id: EntryId;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  locale: Locale;
  name?: Name;
  description?: Description;
  [k: string]: any;
}

    }
    export namespace dashboard_widgets {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type DeletedAt = string;
export type Extension = string;
export type Column = number;
export type DashboardId = number;
export type Pinned = number;

export interface DashboardWidgets {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  deleted_at?: DeletedAt;
  extension: Extension;
  column: Column;
  dashboard_id: DashboardId;
  pinned?: Pinned;
  [k: string]: any;
}

    }
    export namespace dashboard_widgets_allowed_roles {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type RelatedId = number;
export type SortOrder = number;

export interface DashboardWidgetsAllowedRoles {
  id: Id;
  entry_id: EntryId;
  related_id: RelatedId;
  sort_order?: SortOrder;
  [k: string]: any;
}

    }
    export namespace dashboard_widgets_translations {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Locale = string;
export type Title = string;
export type Description = string;

export interface DashboardWidgetsTranslations {
  id: Id;
  entry_id: EntryId;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  locale: Locale;
  title?: Title;
  description?: Description;
  [k: string]: any;
}

    }
    export namespace departments_department {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type DeletedAt = string;
export type Name = string;
export type Slug = string;
export type Description = string;
export type Enabled = number;

export interface DepartmentsDepartment {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  deleted_at?: DeletedAt;
  name: Name;
  slug: Slug;
  description?: Description;
  enabled?: Enabled;
  [k: string]: any;
}

    }
    export namespace deployment_repositories {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Name = string;
export type TeamId = number;
export type Meta = string;
export type FetchedAt = string;

export interface DeploymentRepositories {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  name: Name;
  team_id: TeamId;
  meta?: Meta;
  fetched_at?: FetchedAt;
  [k: string]: any;
}

    }
    export namespace deployment_repositories_allowed_roles {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type RelatedId = number;
export type SortOrder = number;

export interface DeploymentRepositoriesAllowedRoles {
  id: Id;
  entry_id: EntryId;
  related_id: RelatedId;
  sort_order?: SortOrder;
  [k: string]: any;
}

    }
    export namespace deployment_repositories_allowed_users {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type RelatedId = number;
export type SortOrder = number;

export interface DeploymentRepositoriesAllowedUsers {
  id: Id;
  entry_id: EntryId;
  related_id: RelatedId;
  sort_order?: SortOrder;
  [k: string]: any;
}

    }
    export namespace deployment_teams {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type WorkspaceId = string;
export type AccountUsername = string;
export type AccountPassword = string;
export type Meta = string;
export type FetchedAt = string;

export interface DeploymentTeams {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  workspace_id: WorkspaceId;
  account_username: AccountUsername;
  account_password: AccountPassword;
  meta?: Meta;
  fetched_at?: FetchedAt;
  [k: string]: any;
}

    }
    export namespace deployment_teams_allowed_roles {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type RelatedId = number;
export type SortOrder = number;

export interface DeploymentTeamsAllowedRoles {
  id: Id;
  entry_id: EntryId;
  related_id: RelatedId;
  sort_order?: SortOrder;
  [k: string]: any;
}

    }
    export namespace deployment_teams_allowed_users {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type RelatedId = number;
export type SortOrder = number;

export interface DeploymentTeamsAllowedUsers {
  id: Id;
  entry_id: EntryId;
  related_id: RelatedId;
  sort_order?: SortOrder;
  [k: string]: any;
}

    }
    export namespace divider_link_type_dividers {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;

export interface DividerLinkTypeDividers {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  [k: string]: any;
}

    }
    export namespace failed_jobs {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type Connection = string;
export type Queue = string;
export type Payload = string;
export type Exception = string;
export type FailedAt = string;

export interface FailedJobs {
  id: Id;
  connection: Connection;
  queue: Queue;
  payload: Payload;
  exception: Exception;
  failed_at: FailedAt;
  [k: string]: any;
}

    }
    export namespace faq_categories {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Name = string;
export type Slug = string;
export type Color = string;

export interface FaqCategories {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  name: Name;
  slug: Slug;
  color: Color;
  [k: string]: any;
}

    }
    export namespace faq_questions {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type CategoryId = number;
export type Question = string;
export type Answer = string;

export interface FaqQuestions {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  category_id: CategoryId;
  question: Question;
  answer?: Answer;
  [k: string]: any;
}

    }
    export namespace files_disks {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type DeletedAt = string;
export type Name = string;
export type Slug = string;
export type Adapter = string;
export type Description = string;

export interface FilesDisks {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  deleted_at?: DeletedAt;
  name: Name;
  slug: Slug;
  adapter: Adapter;
  description?: Description;
  [k: string]: any;
}

    }
    export namespace files_files {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type DeletedAt = string;
export type Name = string;
export type DiskId = number;
export type FolderId = number;
export type Extension = string;
export type Size = number;
export type MimeType = string;
export type Keywords = string;
export type Height = string;
export type Width = string;
export type AltText = string;
export type Title = string;
export type Caption = string;
export type Description = string;
export type StrId = string;

export interface FilesFiles {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  deleted_at?: DeletedAt;
  name: Name;
  disk_id: DiskId;
  folder_id: FolderId;
  extension: Extension;
  size: Size;
  mime_type: MimeType;
  keywords?: Keywords;
  height?: Height;
  width?: Width;
  alt_text?: AltText;
  title?: Title;
  caption?: Caption;
  description?: Description;
  str_id: StrId;
  [k: string]: any;
}

    }
    export namespace files_folders {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type DeletedAt = string;
export type DiskId = number;
export type Name = string;
export type Slug = string;
export type Description = string;
export type AllowedTypes = string;
export type StrId = string;

export interface FilesFolders {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  deleted_at?: DeletedAt;
  disk_id: DiskId;
  name: Name;
  slug: Slug;
  description?: Description;
  allowed_types?: AllowedTypes;
  str_id: StrId;
  [k: string]: any;
}

    }
    export namespace header_link_type_headers {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;

export interface HeaderLinkTypeHeaders {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  [k: string]: any;
}

    }
    export namespace header_link_type_headers_translations {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Locale = string;
export type Title = string;

export interface HeaderLinkTypeHeadersTranslations {
  id: Id;
  entry_id: EntryId;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  locale: Locale;
  title?: Title;
  [k: string]: any;
}

    }
    export namespace jobs {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type Queue = string;
export type Payload = string;
export type Attempts = number;
export type ReservedAt = number;
export type AvailableAt = number;
export type CreatedAt = number;

export interface Jobs {
  id: Id;
  queue: Queue;
  payload: Payload;
  attempts: Attempts;
  reserved_at?: ReservedAt;
  available_at: AvailableAt;
  created_at: CreatedAt;
  [k: string]: any;
}

    }
    export namespace label_link_type_labels {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;

export interface LabelLinkTypeLabels {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  [k: string]: any;
}

    }
    export namespace label_link_type_labels_translations {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Locale = string;
export type Title = string;
export type Subtitle = string;
export type Description = string;

export interface LabelLinkTypeLabelsTranslations {
  id: Id;
  entry_id: EntryId;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  locale: Locale;
  title?: Title;
  subtitle?: Subtitle;
  description?: Description;
  [k: string]: any;
}

    }
    export namespace menus_links {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type DeletedAt = string;
export type MenuId = number;
export type Type = string;
export type EntryId = number;
export type EntryType = string;
export type Target = string;
export type Class = string;
export type ParentId = number;
export type Icon = string;
export type Hash = string;
export type Querystring = string;

export interface MenusLinks {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  deleted_at?: DeletedAt;
  menu_id: MenuId;
  type: Type;
  entry_id: EntryId;
  entry_type: EntryType;
  target: Target;
  class?: Class;
  parent_id?: ParentId;
  icon?: Icon;
  hash?: Hash;
  querystring?: Querystring;
  [k: string]: any;
}

    }
    export namespace menus_links_allowed_roles {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type RelatedId = number;
export type SortOrder = number;

export interface MenusLinksAllowedRoles {
  id: Id;
  entry_id: EntryId;
  related_id: RelatedId;
  sort_order?: SortOrder;
  [k: string]: any;
}

    }
    export namespace menus_menus {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type DeletedAt = string;
export type Slug = string;

export interface MenusMenus {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  deleted_at?: DeletedAt;
  slug: Slug;
  [k: string]: any;
}

    }
    export namespace menus_menus_allowed_roles {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type RelatedId = number;
export type SortOrder = number;

export interface MenusMenusAllowedRoles {
  id: Id;
  entry_id: EntryId;
  related_id: RelatedId;
  sort_order?: SortOrder;
  [k: string]: any;
}

    }
    export namespace menus_menus_translations {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Locale = string;
export type Name = string;
export type Description = string;

export interface MenusMenusTranslations {
  id: Id;
  entry_id: EntryId;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  locale: Locale;
  name?: Name;
  description?: Description;
  [k: string]: any;
}

    }
    export namespace migrations {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type Migration = string;
export type Batch = number;

export interface Migrations {
  id: Id;
  migration: Migration;
  batch: Batch;
  [k: string]: any;
}

    }
    export namespace module_link_type_modules {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Key = string;

export interface ModuleLinkTypeModules {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  key: Key;
  [k: string]: any;
}

    }
    export namespace module_link_type_modules_translations {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Locale = string;
export type Title = string;
export type Description = string;

export interface ModuleLinkTypeModulesTranslations {
  id: Id;
  entry_id: EntryId;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  locale: Locale;
  title?: Title;
  description?: Description;
  [k: string]: any;
}

    }
    export namespace notifications {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = string;
export type Type = string;
export type NotifiableType = string;
export type NotifiableId = number;
export type Data = string;
export type ReadAt = string;
export type CreatedAt = string;
export type UpdatedAt = string;

export interface Notifications {
  id: Id;
  type: Type;
  notifiable_type: NotifiableType;
  notifiable_id: NotifiableId;
  data: Data;
  read_at?: ReadAt;
  created_at?: CreatedAt;
  updated_at?: UpdatedAt;
  [k: string]: any;
}

    }
    export namespace preferences_preferences {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type UserId = number;
export type Key = string;
export type Value = string;

export interface PreferencesPreferences {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  user_id: UserId;
  key: Key;
  value?: Value;
  [k: string]: any;
}

    }
    export namespace requester_role_type_categories {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Name = string;
export type Slug = string;
export type Description = string;

export interface RequesterRoleTypeCategories {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  name: Name;
  slug: Slug;
  description?: Description;
  [k: string]: any;
}

    }
    export namespace requester_role_type_groups {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Name = string;
export type Slug = string;

export interface RequesterRoleTypeGroups {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  name: Name;
  slug: Slug;
  [k: string]: any;
}

    }
    export namespace requester_role_type_intake {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type ClientId = number;
export type IntakeDate = string;
export type RedirectingInstanceId = number;
export type CustomRedirectingInstance = string;
export type Contact = string;
export type Phone = string;
export type Email = string;
export type CustomInvolvedInstances = string;
export type Situation = string;
export type ExtraContactInformation = string;
export type HasCaretaker = number;
export type IsCaretakerKnown = number;
export type AgreeWithSocialMediaPolicy = number;
export type FreeField = string;
export type MatchIsSmoking = number;
export type MatchHasPets = number;
export type Payed = number;
export type JoinEffectMeeting = number;
export type EffectMeetingInfo = string;
export type DepartmentId = number;

export interface RequesterRoleTypeIntake {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  client_id?: ClientId;
  intake_date?: IntakeDate;
  redirecting_instance_id?: RedirectingInstanceId;
  custom_redirecting_instance?: CustomRedirectingInstance;
  contact?: Contact;
  phone?: Phone;
  email?: Email;
  custom_involved_instances?: CustomInvolvedInstances;
  situation?: Situation;
  extra_contact_information?: ExtraContactInformation;
  has_caretaker?: HasCaretaker;
  is_caretaker_known?: IsCaretakerKnown;
  agree_with_social_media_policy?: AgreeWithSocialMediaPolicy;
  free_field?: FreeField;
  match_is_smoking?: MatchIsSmoking;
  match_has_pets?: MatchHasPets;
  payed?: Payed;
  join_effect_meeting?: JoinEffectMeeting;
  effect_meeting_info?: EffectMeetingInfo;
  department_id: DepartmentId;
  [k: string]: any;
}

    }
    export namespace requester_role_type_intake_involved_instances {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type RelatedId = number;
export type SortOrder = number;

export interface RequesterRoleTypeIntakeInvolvedInstances {
  id: Id;
  entry_id: EntryId;
  related_id: RelatedId;
  sort_order?: SortOrder;
  [k: string]: any;
}

    }
    export namespace requester_role_type_intake_match_target_groups {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type RelatedId = number;
export type SortOrder = number;

export interface RequesterRoleTypeIntakeMatchTargetGroups {
  id: Id;
  entry_id: EntryId;
  related_id: RelatedId;
  sort_order?: SortOrder;
  [k: string]: any;
}

    }
    export namespace requester_role_type_matches {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type DateStart = string;
export type DateEnd = string;
export type Hours = string;
export type Frequency = string;
export type IsClosed = number;
export type ReasonIsClosedId = number;
export type DateClose = string;

export interface RequesterRoleTypeMatches {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  date_start?: DateStart;
  date_end?: DateEnd;
  hours?: Hours;
  frequency?: Frequency;
  is_closed?: IsClosed;
  reason_is_closed_id?: ReasonIsClosedId;
  date_close?: DateClose;
  [k: string]: any;
}

    }
    export namespace requester_role_type_reason_closed {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Slug = string;

export interface RequesterRoleTypeReasonClosed {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  slug: Slug;
  [k: string]: any;
}

    }
    export namespace requester_role_type_reason_closed_translations {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Locale = string;
export type Name = string;

export interface RequesterRoleTypeReasonClosedTranslations {
  id: Id;
  entry_id: EntryId;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  locale: Locale;
  name?: Name;
  [k: string]: any;
}

    }
    export namespace requester_role_type_reason_unfilled {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Name = string;
export type Slug = string;

export interface RequesterRoleTypeReasonUnfilled {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  name: Name;
  slug: Slug;
  [k: string]: any;
}

    }
    export namespace requester_role_type_requests {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type DateOpen = string;
export type DateClose = string;
export type DateStart = string;
export type DateEnd = string;
export type TimeStart = string;
export type TimeEnd = string;
export type ClientId = number;
export type DepartmentId = number;
export type Availability = string;
export type CategoryId = number;
export type Subject = string;
export type MatchId = number;
export type Nature = string;
export type Frequency = string;
export type Hours = string;
export type Memo = string;
export type Info = string;
export type ExternalInfo = string;
export type IsClosed = number;
export type ReasonIsClosedId = number;
export type ReasonNotFilledRequestId = number;

export interface RequesterRoleTypeRequests {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  date_open?: DateOpen;
  date_close?: DateClose;
  date_start?: DateStart;
  date_end?: DateEnd;
  time_start?: TimeStart;
  time_end?: TimeEnd;
  client_id: ClientId;
  department_id: DepartmentId;
  availability?: Availability;
  category_id: CategoryId;
  subject: Subject;
  match_id?: MatchId;
  nature?: Nature;
  frequency?: Frequency;
  hours?: Hours;
  memo?: Memo;
  info?: Info;
  external_info?: ExternalInfo;
  is_closed?: IsClosed;
  reason_is_closed_id?: ReasonIsClosedId;
  reason_not_filled_request_id?: ReasonNotFilledRequestId;
  [k: string]: any;
}

    }
    export namespace search_items {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Title = string;
export type Description = string;
export type Keywords = string;
export type EntryId = number;
export type EntryType = string;
export type StreamId = number;
export type Locale = string;
export type Searchable = string;

export interface SearchItems {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  title?: Title;
  description?: Description;
  keywords?: Keywords;
  entry_id: EntryId;
  entry_type: EntryType;
  stream_id: StreamId;
  locale: Locale;
  searchable?: Searchable;
  [k: string]: any;
}

    }
    export namespace sessions {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = string;
export type UserId = number;
export type IpAddress = string;
export type UserAgent = string;
export type Payload = string;
export type LastActivity = number;

export interface Sessions {
  id: Id;
  user_id?: UserId;
  ip_address?: IpAddress;
  user_agent?: UserAgent;
  payload: Payload;
  last_activity: LastActivity;
  [k: string]: any;
}

    }
    export namespace settings_settings {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Key = string;
export type Value = string;

export interface SettingsSettings {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  key: Key;
  value?: Value;
  [k: string]: any;
}

    }
    export namespace streams_assignments {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type StreamId = number;
export type FieldId = number;
export type Config = string;
export type Unique = number;
export type Required = number;
export type Searchable = number;
export type Translatable = number;
export type Versionable = number;

export interface StreamsAssignments {
  id: Id;
  sort_order: SortOrder;
  stream_id: StreamId;
  field_id: FieldId;
  config: Config;
  unique: Unique;
  required: Required;
  searchable: Searchable;
  translatable: Translatable;
  versionable: Versionable;
  [k: string]: any;
}

    }
    export namespace streams_assignments_translations {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type AssignmentId = number;
export type Locale = string;
export type Label = string;
export type Warning = string;
export type Placeholder = string;
export type Instructions = string;

export interface StreamsAssignmentsTranslations {
  id: Id;
  assignment_id: AssignmentId;
  locale: Locale;
  label?: Label;
  warning?: Warning;
  placeholder?: Placeholder;
  instructions?: Instructions;
  [k: string]: any;
}

    }
    export namespace streams_fields {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type Namespace = string;
export type Slug = string;
export type Type = string;
export type Config = string;
export type Locked = number;

export interface StreamsFields {
  id: Id;
  namespace: Namespace;
  slug: Slug;
  type: Type;
  config: Config;
  locked: Locked;
  [k: string]: any;
}

    }
    export namespace streams_fields_translations {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type FieldId = number;
export type Locale = string;
export type Name = string;
export type Placeholder = string;
export type Warning = string;
export type Instructions = string;

export interface StreamsFieldsTranslations {
  id: Id;
  field_id: FieldId;
  locale: Locale;
  name?: Name;
  placeholder?: Placeholder;
  warning?: Warning;
  instructions?: Instructions;
  [k: string]: any;
}

    }
    export namespace streams_locks {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type LockedAt = string;
export type LockedById = number;
export type LockableId = number;
export type LockableType = string;
export type Url = string;

export interface StreamsLocks {
  id: Id;
  locked_at: LockedAt;
  locked_by_id: LockedById;
  lockable_id: LockableId;
  lockable_type: LockableType;
  url: Url;
  [k: string]: any;
}

    }
    export namespace streams_streams {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type Namespace = string;
export type Slug = string;
export type Prefix = string;
export type TitleColumn = string;
export type OrderBy = string;
export type Locked = number;
export type Hidden = number;
export type Sortable = number;
export type Searchable = number;
export type Trashable = number;
export type Translatable = number;
export type Versionable = number;
export type Config = string;

export interface StreamsStreams {
  id: Id;
  sort_order?: SortOrder;
  namespace: Namespace;
  slug: Slug;
  prefix?: Prefix;
  title_column: TitleColumn;
  order_by: OrderBy;
  locked: Locked;
  hidden: Hidden;
  sortable: Sortable;
  searchable: Searchable;
  trashable: Trashable;
  translatable: Translatable;
  versionable: Versionable;
  config: Config;
  [k: string]: any;
}

    }
    export namespace streams_streams_translations {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type StreamId = number;
export type Locale = string;
export type Name = string;
export type Description = string;

export interface StreamsStreamsTranslations {
  id: Id;
  stream_id: StreamId;
  locale: Locale;
  name?: Name;
  description?: Description;
  [k: string]: any;
}

    }
    export namespace streams_versions {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Version = number;
export type CreatedAt = string;
export type CreatedById = number;
export type VersionableId = number;
export type VersionableType = string;
export type IpAddress = string;
export type Model = string;
export type Data = string;

export interface StreamsVersions {
  version: Version;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  versionable_id: VersionableId;
  versionable_type: VersionableType;
  ip_address: IpAddress;
  model: Model;
  data: Data;
  [k: string]: any;
}

    }
    export namespace test {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type UserId = number;
export type ClientId = number;
export type DepartmentId = number;
export type RoleId = number;

export interface Test {
  id: Id;
  user_id: UserId;
  client_id: ClientId;
  department_id: DepartmentId;
  role_id: RoleId;
  [k: string]: any;
}

    }
    export namespace todos_todos {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Subject = string;
export type Date = string;
export type Body = string;
export type RecipientId = number;

export interface TodosTodos {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  subject: Subject;
  date?: Date;
  body?: Body;
  recipient_id: RecipientId;
  [k: string]: any;
}

    }
    export namespace url_link_type_urls {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Url = string;

export interface UrlLinkTypeUrls {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  url: Url;
  [k: string]: any;
}

    }
    export namespace url_link_type_urls_translations {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Locale = string;
export type Title = string;
export type Description = string;

export interface UrlLinkTypeUrlsTranslations {
  id: Id;
  entry_id: EntryId;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  locale: Locale;
  title?: Title;
  description?: Description;
  [k: string]: any;
}

    }
    export namespace users_roles {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type DeletedAt = string;
export type Slug = string;
export type Permissions = string;

export interface UsersRoles {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  deleted_at?: DeletedAt;
  slug: Slug;
  permissions?: Permissions;
  [k: string]: any;
}

    }
    export namespace users_roles_translations {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Locale = string;
export type Name = string;
export type Description = string;

export interface UsersRolesTranslations {
  id: Id;
  entry_id: EntryId;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  locale: Locale;
  name?: Name;
  description?: Description;
  [k: string]: any;
}

    }
    export namespace users_users {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type DeletedAt = string;
export type DepartmentId = number;
export type Email = string;
export type Username = string;
export type Password = string;
export type DisplayName = string;
export type FirstName = string;
export type LastName = string;
export type Activated = number;
export type Enabled = number;
export type Permissions = string;
export type LastLoginAt = string;
export type RememberToken = string;
export type ActivationCode = string;
export type ResetCode = string;
export type LastActivityAt = string;
export type IpAddress = string;
export type StrId = string;

export interface UsersUsers {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  deleted_at?: DeletedAt;
  department_id?: DepartmentId;
  email: Email;
  username: Username;
  password: Password;
  display_name: DisplayName;
  first_name?: FirstName;
  last_name?: LastName;
  activated?: Activated;
  enabled?: Enabled;
  permissions?: Permissions;
  last_login_at?: LastLoginAt;
  remember_token?: RememberToken;
  activation_code?: ActivationCode;
  reset_code?: ResetCode;
  last_activity_at?: LastActivityAt;
  ip_address?: IpAddress;
  str_id: StrId;
  [k: string]: any;
}

    }
    export namespace users_users_departments {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type RelatedId = number;
export type SortOrder = number;

export interface UsersUsersDepartments {
  id: Id;
  entry_id: EntryId;
  related_id: RelatedId;
  sort_order?: SortOrder;
  [k: string]: any;
}

    }
    export namespace users_users_roles {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type RelatedId = number;
export type SortOrder = number;

export interface UsersUsersRoles {
  id: Id;
  entry_id: EntryId;
  related_id: RelatedId;
  sort_order?: SortOrder;
  [k: string]: any;
}

    }
    export namespace volunteer_role_type_intake {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type ClientId = number;
export type DepartmentId = number;
export type IntakeDate = string;
export type Information = string;
export type EducationLevelId = number;
export type HasDriverLicense = string;
export type Transportation = string;
export type References = string;
export type FreeField = string;
export type MatchFromDate = string;
export type MatchEnabled = number;
export type MatchSmoking = number;
export type MatchPets = number;
export type MatchAvailability = string;
export type MatchAgeRanges = string;

export interface VolunteerRoleTypeIntake {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  client_id?: ClientId;
  department_id: DepartmentId;
  intake_date?: IntakeDate;
  information?: Information;
  education_level_id?: EducationLevelId;
  has_driver_license?: HasDriverLicense;
  transportation?: Transportation;
  references?: References;
  free_field?: FreeField;
  match_from_date?: MatchFromDate;
  match_enabled?: MatchEnabled;
  match_smoking?: MatchSmoking;
  match_pets?: MatchPets;
  match_availability?: MatchAvailability;
  match_age_ranges?: MatchAgeRanges;
  [k: string]: any;
}

    }
    export namespace volunteer_role_type_intake_match_requester_categories {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type RelatedId = number;
export type SortOrder = number;

export interface VolunteerRoleTypeIntakeMatchRequesterCategories {
  id: Id;
  entry_id: EntryId;
  related_id: RelatedId;
  sort_order?: SortOrder;
  [k: string]: any;
}

    }
    export namespace volunteer_role_type_intake_match_requester_groups {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type RelatedId = number;
export type SortOrder = number;

export interface VolunteerRoleTypeIntakeMatchRequesterGroups {
  id: Id;
  entry_id: EntryId;
  related_id: RelatedId;
  sort_order?: SortOrder;
  [k: string]: any;
}

    }
}