<?php

namespace Pyro\Platform\Http;

use Pyro\Platform\Support\Enum;
use Teapot\StatusCode\All;

/**
 * @method static HttpStatus PROCESSING()
 * @method static HttpStatus UNORDERED_COLLECTION()
 * @method static HttpStatus MULTI_STATUS()
 * @method static HttpStatus UNPROCESSABLE_ENTITY()
 * @method static HttpStatus ENTITY_LOCKED()
 * @method static HttpStatus METHOD_FAILURE()
 * @method static HttpStatus FAILED_DEPENDENCY()
 * @method static HttpStatus INSUFFICIENT_STORAGE()
 * @method static HttpStatus ALREADY_REPORTED()
 * @method static HttpStatus LOOP_DETECTED()
 * @method static HttpStatus POLICY_NOT_FULFILLED()
 * @method static HttpStatus BAD_MAPPING()
 * @method static HttpStatus VARIANT_ALSO_NEGOTIATES()
 * @method static HttpStatus PARAMETER_NOT_UNDERSTOOD()
 * @method static HttpStatus CONFERENCE_NOT_FOUND()
 * @method static HttpStatus NOT_ENOUGH_BANDWIDTH()
 * @method static HttpStatus SESSION_NOT_FOUND()
 * @method static HttpStatus METHOD_NOT_VALID_IN_THIS_STATE()
 * @method static HttpStatus HEADER_FIELD_NOT_VALID_FOR_RESOURCE()
 * @method static HttpStatus INVALID_RANGE()
 * @method static HttpStatus PARAMETER_IS_READ_ONLY()
 * @method static HttpStatus AGGREGATE_OPERATION_NOT_ALLOWED()
 * @method static HttpStatus ONLY_AGGREGATE_OPERATION_ALLOWED()
 * @method static HttpStatus UNSUPPORTED_TRANSPORT()
 * @method static HttpStatus DESTINATION_UNREACHABLE()
 * @method static HttpStatus MULTIPLE_OPTIONS()
 * @method static HttpStatus BREW_FORBIDDEN()
 * @method static HttpStatus IM_A_TEAPOT()
 * @method static HttpStatus CONTINUING()
 * @method static HttpStatus CONTINUE_()
 * @method static HttpStatus SWITCHING_PROTOCOLS()
 * @method static HttpStatus OK()
 * @method static HttpStatus CREATED()
 * @method static HttpStatus ACCEPTED()
 * @method static HttpStatus NON_AUTHORITATIVE_INFORMATION()
 * @method static HttpStatus NON_AUTHORATIVE_INFORMATION()
 * @method static HttpStatus NO_CONTENT()
 * @method static HttpStatus RESET_CONTENT()
 * @method static HttpStatus MULTIPLE_CHOICES()
 * @method static HttpStatus MOVED_PERMANENTLY()
 * @method static HttpStatus FOUND()
 * @method static HttpStatus SEE_OTHER()
 * @method static HttpStatus USE_PROXY()
 * @method static HttpStatus UNUSED()
 * @method static HttpStatus TEMPORARY_REDIRECT()
 * @method static HttpStatus BAD_REQUEST()
 * @method static HttpStatus PAYMENT_REQUIRED()
 * @method static HttpStatus FORBIDDEN()
 * @method static HttpStatus NOT_FOUND()
 * @method static HttpStatus METHOD_NOT_ALLOWED()
 * @method static HttpStatus NOT_ACCEPTABLE()
 * @method static HttpStatus REQUEST_TIMEOUT()
 * @method static HttpStatus CONFLICT()
 * @method static HttpStatus GONE()
 * @method static HttpStatus LENGTH_REQUIRED()
 * @method static HttpStatus PAYLOAD_TOO_LARGE()
 * @method static HttpStatus URI_TOO_LONG()
 * @method static HttpStatus UNSUPPORTED_MEDIA_TYPE()
 * @method static HttpStatus EXPECTATION_FAILED()
 * @method static HttpStatus UPGRADE_REQUIRED()
 * @method static HttpStatus INTERNAL_SERVER_ERROR()
 * @method static HttpStatus NOT_IMPLEMENTED()
 * @method static HttpStatus BAD_GATEWAY()
 * @method static HttpStatus SERVICE_UNAVAILABLE()
 * @method static HttpStatus GATEWAY_TIMEOUT()
 * @method static HttpStatus HTTP_VERSION_NOT_SUPPORTED()
 * @method static HttpStatus NOT_MODIFIED()
 * @method static HttpStatus PRECONDITION_FAILED()
 * @method static HttpStatus PARTIAL_CONTENT()
 * @method static HttpStatus RANGE_NOT_SATISFIABLE()
 * @method static HttpStatus RESPONSE_IS_STALE()
 * @method static HttpStatus REVALIDATION_FAILED()
 * @method static HttpStatus DISCONNECTED_OPERATION()
 * @method static HttpStatus HEURISTIC_EXPIRATION()
 * @method static HttpStatus MISCELLANEOUS_WARNING()
 * @method static HttpStatus TRANSFORMATION_APPLIED()
 * @method static HttpStatus MISCELLANEOUS_PERSISTENT_WARNING()
 * @method static HttpStatus UNAUTHORIZED()
 * @method static HttpStatus PROXY_AUTHENTICATION_REQUIRED()
 * @method static HttpStatus PERMANENT_REDIRECT()
 * @method static HttpStatus MISDIRECTED_REQUEST()
 * @method static HttpStatus UNAVAILABLE_FOR_LEGAL_REASONS()
 * @method static HttpStatus IM_USED()
 * @method static HttpStatus BANDWIDTH_LIMIT_EXCEEDED()
 * @method static HttpStatus ORIGIN_ERROR()
 * @method static HttpStatus ORIGIN_DECLINED_REQUEST()
 * @method static HttpStatus CONNECTION_TIMED_OUT()
 * @method static HttpStatus PROXY_DECLINED_REQUEST()
 * @method static HttpStatus TIMEOUT_OCCURRED()
 * @method static HttpStatus LOGIN_TIMEOUT()
 * @method static HttpStatus RETRY_WITH()
 * @method static HttpStatus BLOCKED_BY_WINDOWS_PARENTAL_CONTROLS()
 * @method static HttpStatus REDIRECT()
 * @method static HttpStatus NO_RESPONSE()
 * @method static HttpStatus REQUEST_HEADER_TOO_LARGE()
 * @method static HttpStatus CERT_ERROR()
 * @method static HttpStatus NO_CERT()
 * @method static HttpStatus HTTP_TO_HTTPS()
 * @method static HttpStatus CLIENT_CLOSED_REQUEST()
 * @method static HttpStatus ENHANCE_YOUR_CALM()
 */
class HttpStatus extends Enum implements All
{

}
