export namespace streams {
    export namespace menus_links {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type DeletedAt = string;
export type MenuId = number;
export type Type = string;
export type EntryId = number;
export type EntryType = string;
export type Target = string;
export type Class = string;
export type ParentId = number;
export type Icon = string;

export interface MenusLinks {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  deleted_at?: DeletedAt;
  menu_id: MenuId;
  type: Type;
  entry_id: EntryId;
  entry_type: EntryType;
  target: Target;
  class?: Class;
  parent_id?: ParentId;
  icon?: Icon;
  [k: string]: any;
}

    }
    export namespace applications {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type Name = string;
export type Reference = string;
export type Domain = string;
export type Enabled = number;

export interface Applications {
  id: Id;
  name: Name;
  reference: Reference;
  domain: Domain;
  enabled: Enabled;
  [k: string]: any;
}

    }
    export namespace addons_extensions {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type Namespace = string;
export type Installed = number;
export type Enabled = number;

export interface AddonsExtensions {
  id: Id;
  namespace: Namespace;
  installed: Installed;
  enabled: Enabled;
  [k: string]: any;
}

    }
    export namespace addons_modules {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type Namespace = string;
export type Installed = number;
export type Enabled = number;

export interface AddonsModules {
  id: Id;
  namespace: Namespace;
  installed: Installed;
  enabled: Enabled;
  [k: string]: any;
}

    }
    export namespace cache {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Key = string;
export type Value = string;
export type Expiration = number;

export interface Cache {
  key: Key;
  value: Value;
  expiration: Expiration;
  [k: string]: any;
}

    }
    export namespace clients_clients {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type DeletedAt = string;
export type UserId = number;
export type Firstname = string;
export type Lastname = string;
export type Initials = string;
export type MaidenName = string;
export type Gender = string;
export type Birthdate = string;
export type Address = string;
export type Housenumber = string;
export type Postcode = string;
export type City = string;
export type Nationality = string;
export type MaritalStatus = string;
export type PhoneNumber = string;
export type MobileNumber = string;
export type Email = string;
export type BankAccountNumber = number;
export type ReceiveCorrespondence = number;
export type CorrespondenceAbout = string;
export type CorrespondenceVia = string;
export type Specials = string;
export type SignupDate = string;
export type Memo = string;
export type DepartmentId = number;

export interface ClientsClients {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  deleted_at?: DeletedAt;
  user_id?: UserId;
  firstname: Firstname;
  lastname: Lastname;
  initials?: Initials;
  maiden_name?: MaidenName;
  gender?: Gender;
  birthdate?: Birthdate;
  address?: Address;
  housenumber?: Housenumber;
  postcode?: Postcode;
  city?: City;
  nationality?: Nationality;
  marital_status?: MaritalStatus;
  phone_number?: PhoneNumber;
  mobile_number?: MobileNumber;
  email?: Email;
  bank_account_number?: BankAccountNumber;
  receive_correspondence?: ReceiveCorrespondence;
  correspondence_about?: CorrespondenceAbout;
  correspondence_via?: CorrespondenceVia;
  specials?: Specials;
  signup_date?: SignupDate;
  memo?: Memo;
  department_id?: DepartmentId;
  [k: string]: any;
}

    }
    export namespace clients_clients_roles {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type RelatedId = number;
export type SortOrder = number;

export interface ClientsClientsRoles {
  id: Id;
  entry_id: EntryId;
  related_id: RelatedId;
  sort_order?: SortOrder;
  [k: string]: any;
}

    }
    export namespace clients_documents {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Name = string;
export type ClientId = number;
export type FileId = number;

export interface ClientsDocuments {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  name: Name;
  client_id: ClientId;
  file_id: FileId;
  [k: string]: any;
}

    }
    export namespace clients_roles {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Name = string;
export type Slug = string;
export type Color = string;
export type Description = string;

export interface ClientsRoles {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  name: Name;
  slug: Slug;
  color?: Color;
  description?: Description;
  [k: string]: any;
}

    }
    export namespace configuration_configuration {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Scope = string;
export type Key = string;
export type Value = string;

export interface ConfigurationConfiguration {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  scope: Scope;
  key: Key;
  value?: Value;
  [k: string]: any;
}

    }
    export namespace dashboard_dashboards {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type DeletedAt = string;
export type Slug = string;
export type Layout = string;

export interface DashboardDashboards {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  deleted_at?: DeletedAt;
  slug: Slug;
  layout: Layout;
  [k: string]: any;
}

    }
    export namespace dashboard_dashboards_allowed_roles {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type RelatedId = number;
export type SortOrder = number;

export interface DashboardDashboardsAllowedRoles {
  id: Id;
  entry_id: EntryId;
  related_id: RelatedId;
  sort_order?: SortOrder;
  [k: string]: any;
}

    }
    export namespace dashboard_dashboards_translations {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Locale = string;
export type Name = string;
export type Description = string;

export interface DashboardDashboardsTranslations {
  id: Id;
  entry_id: EntryId;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  locale: Locale;
  name?: Name;
  description?: Description;
  [k: string]: any;
}

    }
    export namespace dashboard_widgets {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type DeletedAt = string;
export type Extension = string;
export type Column = number;
export type DashboardId = number;
export type Pinned = number;

export interface DashboardWidgets {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  deleted_at?: DeletedAt;
  extension: Extension;
  column: Column;
  dashboard_id: DashboardId;
  pinned?: Pinned;
  [k: string]: any;
}

    }
    export namespace dashboard_widgets_allowed_roles {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type RelatedId = number;
export type SortOrder = number;

export interface DashboardWidgetsAllowedRoles {
  id: Id;
  entry_id: EntryId;
  related_id: RelatedId;
  sort_order?: SortOrder;
  [k: string]: any;
}

    }
    export namespace dashboard_widgets_translations {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Locale = string;
export type Title = string;
export type Description = string;

export interface DashboardWidgetsTranslations {
  id: Id;
  entry_id: EntryId;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  locale: Locale;
  title?: Title;
  description?: Description;
  [k: string]: any;
}

    }
    export namespace departments_associations {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type LinkId = number;
export type DepartmentId = number;

export interface DepartmentsAssociations {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  link_id: LinkId;
  department_id: DepartmentId;
  [k: string]: any;
}

    }
    export namespace departments_department {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type DeletedAt = string;
export type Name = string;
export type Slug = string;
export type Description = string;
export type Enabled = number;

export interface DepartmentsDepartment {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  deleted_at?: DeletedAt;
  name: Name;
  slug: Slug;
  description?: Description;
  enabled?: Enabled;
  [k: string]: any;
}

    }
    export namespace divider_link_type_dividers {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;

export interface DividerLinkTypeDividers {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  [k: string]: any;
}

    }
    export namespace documentation_categories {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Slug = string;

export interface DocumentationCategories {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  slug: Slug;
  [k: string]: any;
}

    }
    export namespace documentation_categories_translations {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Locale = string;
export type Name = string;
export type Description = string;

export interface DocumentationCategoriesTranslations {
  id: Id;
  entry_id: EntryId;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  locale: Locale;
  name?: Name;
  description?: Description;
  [k: string]: any;
}

    }
    export namespace documentation_pages {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Path = string;
export type ProjectId = number;
export type Reference = string;
export type ParentId = number;

export interface DocumentationPages {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  path: Path;
  project_id: ProjectId;
  reference: Reference;
  parent_id?: ParentId;
  [k: string]: any;
}

    }
    export namespace documentation_pages_translations {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Locale = string;
export type Title = string;
export type Content = string;
export type Data = string;
export type MetaTitle = string;
export type MetaDescription = string;

export interface DocumentationPagesTranslations {
  id: Id;
  entry_id: EntryId;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  locale: Locale;
  title?: Title;
  content?: Content;
  data?: Data;
  meta_title?: MetaTitle;
  meta_description?: MetaDescription;
  [k: string]: any;
}

    }
    export namespace documentation_projects {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type DeletedAt = string;
export type StrId = string;
export type Slug = string;
export type Documentation = string;
export type Versions = string;
export type Enabled = number;

export interface DocumentationProjects {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  deleted_at?: DeletedAt;
  str_id: StrId;
  slug: Slug;
  documentation: Documentation;
  versions: Versions;
  enabled?: Enabled;
  [k: string]: any;
}

    }
    export namespace documentation_projects_translations {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Locale = string;
export type Name = string;
export type Description = string;

export interface DocumentationProjectsTranslations {
  id: Id;
  entry_id: EntryId;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  locale: Locale;
  name?: Name;
  description?: Description;
  [k: string]: any;
}

    }
    export namespace failed_jobs {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type Connection = string;
export type Queue = string;
export type Payload = string;
export type Exception = string;
export type FailedAt = string;

export interface FailedJobs {
  id: Id;
  connection: Connection;
  queue: Queue;
  payload: Payload;
  exception: Exception;
  failed_at: FailedAt;
  [k: string]: any;
}

    }
    export namespace faq_categories {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Name = string;
export type Slug = string;
export type Color = string;

export interface FaqCategories {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  name: Name;
  slug: Slug;
  color: Color;
  [k: string]: any;
}

    }
    export namespace faq_questions {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Question = string;
export type Answer = string;
export type CategoryId = number;

export interface FaqQuestions {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  question: Question;
  answer?: Answer;
  category_id: CategoryId;
  [k: string]: any;
}

    }
    export namespace header_link_type_headers {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;

export interface HeaderLinkTypeHeaders {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  [k: string]: any;
}

    }
    export namespace header_link_type_headers_translations {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Locale = string;
export type Title = string;

export interface HeaderLinkTypeHeadersTranslations {
  id: Id;
  entry_id: EntryId;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  locale: Locale;
  title?: Title;
  [k: string]: any;
}

    }
    export namespace html_block_blocks {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;

export interface HtmlBlockBlocks {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  [k: string]: any;
}

    }
    export namespace html_block_blocks_translations {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Locale = string;
export type Html = string;

export interface HtmlBlockBlocksTranslations {
  id: Id;
  entry_id: EntryId;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  locale: Locale;
  html?: Html;
  [k: string]: any;
}

    }
    export namespace jobs {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type Queue = string;
export type Payload = string;
export type Attempts = number;
export type ReservedAt = number;
export type AvailableAt = number;
export type CreatedAt = number;

export interface Jobs {
  id: Id;
  queue: Queue;
  payload: Payload;
  attempts: Attempts;
  reserved_at?: ReservedAt;
  available_at: AvailableAt;
  created_at: CreatedAt;
  [k: string]: any;
}

    }
    export namespace label_link_type_labels {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;

export interface LabelLinkTypeLabels {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  [k: string]: any;
}

    }
    export namespace label_link_type_labels_translations {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Locale = string;
export type Title = string;
export type Subtitle = string;
export type Description = string;

export interface LabelLinkTypeLabelsTranslations {
  id: Id;
  entry_id: EntryId;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  locale: Locale;
  title?: Title;
  subtitle?: Subtitle;
  description?: Description;
  [k: string]: any;
}

    }
    export namespace applications_domains {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type ApplicationId = number;
export type Domain = string;
export type Locale = string;

export interface ApplicationsDomains {
  id: Id;
  application_id: ApplicationId;
  domain: Domain;
  locale: Locale;
  [k: string]: any;
}

    }
    export namespace menus_links_allowed_roles {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type RelatedId = number;
export type SortOrder = number;

export interface MenusLinksAllowedRoles {
  id: Id;
  entry_id: EntryId;
  related_id: RelatedId;
  sort_order?: SortOrder;
  [k: string]: any;
}

    }
    export namespace menus_menus {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type DeletedAt = string;
export type Slug = string;

export interface MenusMenus {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  deleted_at?: DeletedAt;
  slug: Slug;
  [k: string]: any;
}

    }
    export namespace menus_menus_allowed_roles {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type RelatedId = number;
export type SortOrder = number;

export interface MenusMenusAllowedRoles {
  id: Id;
  entry_id: EntryId;
  related_id: RelatedId;
  sort_order?: SortOrder;
  [k: string]: any;
}

    }
    export namespace menus_menus_translations {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Locale = string;
export type Name = string;
export type Description = string;

export interface MenusMenusTranslations {
  id: Id;
  entry_id: EntryId;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  locale: Locale;
  name?: Name;
  description?: Description;
  [k: string]: any;
}

    }
    export namespace migrations {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type Migration = string;
export type Batch = number;

export interface Migrations {
  id: Id;
  migration: Migration;
  batch: Batch;
  [k: string]: any;
}

    }
    export namespace module_link_type_modules {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Link = string;

export interface ModuleLinkTypeModules {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  link: Link;
  [k: string]: any;
}

    }
    export namespace module_link_type_modules_translations {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Locale = string;
export type Title = string;
export type Description = string;

export interface ModuleLinkTypeModulesTranslations {
  id: Id;
  entry_id: EntryId;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  locale: Locale;
  title?: Title;
  description?: Description;
  [k: string]: any;
}

    }
    export namespace news_items {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type DeletedAt = string;
export type Title = string;
export type Slug = string;
export type AuthorId = number;
export type Feed = number;
export type Body = string;

export interface NewsItems {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  deleted_at?: DeletedAt;
  title: Title;
  slug: Slug;
  author_id: AuthorId;
  feed?: Feed;
  body?: Body;
  [k: string]: any;
}

    }
    export namespace notifications {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = string;
export type Type = string;
export type NotifiableType = string;
export type NotifiableId = number;
export type Data = string;
export type ReadAt = string;
export type CreatedAt = string;
export type UpdatedAt = string;

export interface Notifications {
  id: Id;
  type: Type;
  notifiable_type: NotifiableType;
  notifiable_id: NotifiableId;
  data: Data;
  read_at?: ReadAt;
  created_at?: CreatedAt;
  updated_at?: UpdatedAt;
  [k: string]: any;
}

    }
    export namespace pages_pages {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type DeletedAt = string;
export type StrId = string;
export type Slug = string;
export type Path = string;

export interface PagesPages {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  deleted_at?: DeletedAt;
  str_id: StrId;
  slug: Slug;
  path: Path;
  [k: string]: any;
}

    }
    export namespace pages_pages_translations {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Locale = string;
export type Title = string;

export interface PagesPagesTranslations {
  id: Id;
  entry_id: EntryId;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  locale: Locale;
  title?: Title;
  [k: string]: any;
}

    }
    export namespace preferences_preferences {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type UserId = number;
export type Key = string;
export type Value = string;

export interface PreferencesPreferences {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  user_id: UserId;
  key: Key;
  value?: Value;
  [k: string]: any;
}

    }
    export namespace search_items {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Title = string;
export type Description = string;
export type Keywords = string;
export type EntryId = number;
export type EntryType = string;
export type StreamId = number;
export type Locale = string;
export type Searchable = string;

export interface SearchItems {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  title?: Title;
  description?: Description;
  keywords?: Keywords;
  entry_id: EntryId;
  entry_type: EntryType;
  stream_id: StreamId;
  locale: Locale;
  searchable?: Searchable;
  [k: string]: any;
}

    }
    export namespace sessions {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = string;
export type UserId = number;
export type IpAddress = string;
export type UserAgent = string;
export type Payload = string;
export type LastActivity = number;

export interface Sessions {
  id: Id;
  user_id?: UserId;
  ip_address?: IpAddress;
  user_agent?: UserAgent;
  payload: Payload;
  last_activity: LastActivity;
  [k: string]: any;
}

    }
    export namespace settings_settings {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Key = string;
export type Value = string;

export interface SettingsSettings {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  key: Key;
  value?: Value;
  [k: string]: any;
}

    }
    export namespace streams_assignments {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type StreamId = number;
export type FieldId = number;
export type Config = string;
export type Unique = number;
export type Required = number;
export type Searchable = number;
export type Translatable = number;
export type Versionable = number;

export interface StreamsAssignments {
  id: Id;
  sort_order: SortOrder;
  stream_id: StreamId;
  field_id: FieldId;
  config: Config;
  unique: Unique;
  required: Required;
  searchable: Searchable;
  translatable: Translatable;
  versionable: Versionable;
  [k: string]: any;
}

    }
    export namespace streams_assignments_translations {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type AssignmentId = number;
export type Locale = string;
export type Label = string;
export type Warning = string;
export type Placeholder = string;
export type Instructions = string;

export interface StreamsAssignmentsTranslations {
  id: Id;
  assignment_id: AssignmentId;
  locale: Locale;
  label?: Label;
  warning?: Warning;
  placeholder?: Placeholder;
  instructions?: Instructions;
  [k: string]: any;
}

    }
    export namespace streams_fields {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type Namespace = string;
export type Slug = string;
export type Type = string;
export type Config = string;
export type Locked = number;

export interface StreamsFields {
  id: Id;
  namespace: Namespace;
  slug: Slug;
  type: Type;
  config: Config;
  locked: Locked;
  [k: string]: any;
}

    }
    export namespace streams_fields_translations {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type FieldId = number;
export type Locale = string;
export type Name = string;
export type Placeholder = string;
export type Warning = string;
export type Instructions = string;

export interface StreamsFieldsTranslations {
  id: Id;
  field_id: FieldId;
  locale: Locale;
  name?: Name;
  placeholder?: Placeholder;
  warning?: Warning;
  instructions?: Instructions;
  [k: string]: any;
}

    }
    export namespace streams_locks {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type LockedAt = string;
export type LockedById = number;
export type LockableId = number;
export type LockableType = string;
export type Url = string;

export interface StreamsLocks {
  id: Id;
  locked_at: LockedAt;
  locked_by_id: LockedById;
  lockable_id: LockableId;
  lockable_type: LockableType;
  url: Url;
  [k: string]: any;
}

    }
    export namespace streams_streams {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type Namespace = string;
export type Slug = string;
export type Prefix = string;
export type TitleColumn = string;
export type OrderBy = string;
export type Locked = number;
export type Hidden = number;
export type Sortable = number;
export type Searchable = number;
export type Trashable = number;
export type Translatable = number;
export type Versionable = number;
export type Config = string;

export interface StreamsStreams {
  id: Id;
  sort_order?: SortOrder;
  namespace: Namespace;
  slug: Slug;
  prefix?: Prefix;
  title_column: TitleColumn;
  order_by: OrderBy;
  locked: Locked;
  hidden: Hidden;
  sortable: Sortable;
  searchable: Searchable;
  trashable: Trashable;
  translatable: Translatable;
  versionable: Versionable;
  config: Config;
  [k: string]: any;
}

    }
    export namespace streams_streams_translations {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type StreamId = number;
export type Locale = string;
export type Name = string;
export type Description = string;

export interface StreamsStreamsTranslations {
  id: Id;
  stream_id: StreamId;
  locale: Locale;
  name?: Name;
  description?: Description;
  [k: string]: any;
}

    }
    export namespace streams_versions {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Version = number;
export type CreatedAt = string;
export type CreatedById = number;
export type VersionableId = number;
export type VersionableType = string;
export type IpAddress = string;
export type Model = string;
export type Data = string;

export interface StreamsVersions {
  version: Version;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  versionable_id: VersionableId;
  versionable_type: VersionableType;
  ip_address: IpAddress;
  model: Model;
  data: Data;
  [k: string]: any;
}

    }
    export namespace telescope_entries {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Sequence = number;
export type Uuid = string;
export type BatchId = string;
export type FamilyHash = string;
export type ShouldDisplayOnIndex = number;
export type Type = string;
export type Content = string;
export type CreatedAt = string;

export interface TelescopeEntries {
  sequence: Sequence;
  uuid: Uuid;
  batch_id: BatchId;
  family_hash?: FamilyHash;
  should_display_on_index: ShouldDisplayOnIndex;
  type: Type;
  content: Content;
  created_at?: CreatedAt;
  [k: string]: any;
}

    }
    export namespace telescope_entries_tags {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type EntryUuid = string;
export type Tag = string;

export interface TelescopeEntriesTags {
  entry_uuid: EntryUuid;
  tag: Tag;
  [k: string]: any;
}

    }
    export namespace telescope_monitoring {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Tag = string;

export interface TelescopeMonitoring {
  tag: Tag;
  [k: string]: any;
}

    }
    export namespace url_link_type_urls {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Url = string;

export interface UrlLinkTypeUrls {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  url: Url;
  [k: string]: any;
}

    }
    export namespace url_link_type_urls_translations {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Locale = string;
export type Title = string;
export type Description = string;

export interface UrlLinkTypeUrlsTranslations {
  id: Id;
  entry_id: EntryId;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  locale: Locale;
  title?: Title;
  description?: Description;
  [k: string]: any;
}

    }
    export namespace users_roles {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type DeletedAt = string;
export type Slug = string;
export type Permissions = string;

export interface UsersRoles {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  deleted_at?: DeletedAt;
  slug: Slug;
  permissions?: Permissions;
  [k: string]: any;
}

    }
    export namespace users_roles_translations {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Locale = string;
export type Name = string;
export type Description = string;

export interface UsersRolesTranslations {
  id: Id;
  entry_id: EntryId;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  locale: Locale;
  name?: Name;
  description?: Description;
  [k: string]: any;
}

    }
    export namespace users_users {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type DeletedAt = string;
export type Email = string;
export type Username = string;
export type Password = string;
export type DisplayName = string;
export type FirstName = string;
export type LastName = string;
export type Activated = number;
export type Enabled = number;
export type Permissions = string;
export type LastLoginAt = string;
export type RememberToken = string;
export type ActivationCode = string;
export type ResetCode = string;
export type LastActivityAt = string;
export type IpAddress = string;
export type StrId = string;
export type DepartmentId = number;

export interface UsersUsers {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  deleted_at?: DeletedAt;
  email: Email;
  username: Username;
  password: Password;
  display_name: DisplayName;
  first_name?: FirstName;
  last_name?: LastName;
  activated?: Activated;
  enabled?: Enabled;
  permissions?: Permissions;
  last_login_at?: LastLoginAt;
  remember_token?: RememberToken;
  activation_code?: ActivationCode;
  reset_code?: ResetCode;
  last_activity_at?: LastActivityAt;
  ip_address?: IpAddress;
  str_id: StrId;
  department_id?: DepartmentId;
  [k: string]: any;
}

    }
    export namespace users_users_departments {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type RelatedId = number;
export type SortOrder = number;

export interface UsersUsersDepartments {
  id: Id;
  entry_id: EntryId;
  related_id: RelatedId;
  sort_order?: SortOrder;
  [k: string]: any;
}

    }
    export namespace users_users_roles {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type RelatedId = number;
export type SortOrder = number;

export interface UsersUsersRoles {
  id: Id;
  entry_id: EntryId;
  related_id: RelatedId;
  sort_order?: SortOrder;
  [k: string]: any;
}

    }
    export namespace wysiwyg_block_blocks {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type SortOrder = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;

export interface WysiwygBlockBlocks {
  id: Id;
  sort_order?: SortOrder;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  [k: string]: any;
}

    }
    export namespace wysiwyg_block_blocks_translations {
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type EntryId = number;
export type CreatedAt = string;
export type CreatedById = number;
export type UpdatedAt = string;
export type UpdatedById = number;
export type Locale = string;
export type Content = string;

export interface WysiwygBlockBlocksTranslations {
  id: Id;
  entry_id: EntryId;
  created_at: CreatedAt;
  created_by_id?: CreatedById;
  updated_at?: UpdatedAt;
  updated_by_id?: UpdatedById;
  locale: Locale;
  content?: Content;
  [k: string]: any;
}

    }
}